"""'Init'

Revision ID: 1de249ddfb45
Revises: 6cd6a3454dc0
Create Date: 2024-06-23 23:17:19.912833

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1de249ddfb45'
down_revision: Union[str, None] = '6cd6a3454dc0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contacts', sa.Column('created_by_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'contacts', 'users', ['created_by_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'contacts', type_='foreignkey')
    op.drop_column('contacts', 'created_by_id')
    # ### end Alembic commands ###
